---
- name: configure homebrew taps
  homebrew_tap: name={{ item }} state=present
  with_items:
    - homebrew/science
    - homebrew/dupes
    - homebrew/versions
    - caskroom/cask

#- name: update homebrew and all packages
#  homebrew: update_homebrew=yes upgrade_all=yes

- name: install common homebrew packages
  homebrew: name={{ item }} state=present
  with_items:
    - brew-cask

- name: install common homebrew casks
  homebrew_cask: name={{ item }} state=present
  with_items:
    - google-chrome
    - virtualbox
